### ISSUE TITLE
Change in no of output classes

### ISSUE THREAD

**Issue by Geera23** [MuhammedBuyukkinaci/TensorFlow-Multiclass-Image-Classification-using-CNN-s#2]
i have used your architecture to train and test for 8 output classes and im finding it bit difficult to do that. im getting a value error.
ValueError: Cannot feed value of shape (40, 227, 227, 3) for Tensor 'Placeholder_1:0', which has shape '(?, 8)'
can u help me solving it?

**Comment by MuhammedBuyukkinaci** [comment]
We made a skype session and reviewed your code.
