### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by agungsugiarto** [MuhammedBuyukkinaci/TensorFlow-Multiclass-Image-Classification-using-CNN-s#6]
Can you share how to training dataset from image to numpy?

**Comment by MuhammedBuyukkinaci** [comment]
Hi,

Thanks for your interest.

1) Download data from [here](https://www.kaggle.com/mbkinaci/chair-kitchen-knife-saucepan). Then,

2) Put downloaded images in one folder.

3) Fine-tune the below code 

```
#Labeling data
def label_img(img):
    word_label = img.split('_')[0]
    if word_label == 'chair': return [1,0,0,0]
    elif word_label == 'kitchen': return [0,1,0,0]
    elif word_label == 'knife': return [0,0,1,0]
    elif word_label == 'saucepan': return [0,0,0,1]

#Function for importing data(images) from train directory.
def create_train_data():
    training_data = []
    for img in tqdm(os.listdir(THE_PATH_OF_IMAGES)):
        label = label_img(img)
        path = os.path.join(THE_PATH_OF_IMAGES,img)
        img = cv2.imread(path,1)
        img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))
        training_data.append([np.array(img),np.array(label)])
    shuffle(training_data)
    np.save('train_data_bi.npy', training_data)
    return training_data

create_train_data()
```

**Comment by agungsugiarto** [comment]
hmm.. my dataset

**Comment by agungsugiarto** [comment]
Thanks, but i got this error like this

`error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'`

![image](https://user-images.githubusercontent.com/10989147/60703161-431e9a80-9f2b-11e9-850b-21fe7fdfd736.png)

**Comment by MuhammedBuyukkinaci** [comment]
Define a varaible named IMG_SIZE like below:
`
IMG_SIZE =227
`

**Comment by MuhammedBuyukkinaci** [comment]
Closing the issue.
